USE [master]
GO

CREATE LOGIN [CLASETORIAL] WITH PASSWORD=N'0123456789', DEFAULT_DATABASE=[testing], DEFAULT_LANGUAGE=[us_english], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

use testing
create user [CLASETORIAL] from login [CLASETORIAL];

CREATE SCHEMA DATA_IMPORT;

drop table DATA_IMPORT.TB_TMP_RAW_BOVESPA_CLASSIFICACAO_SETORIAL
CREATE TABLE DATA_IMPORT.TB_TMP_RAW_BOVESPA_CLASSIFICACAO_SETORIAL
(
	NM_SETOR_ECONOMICO		VARCHAR(100)	NOT	NULL
	,NM_SUBSETOR_ECONOMICO	VARCHAR(100)	NOT	NULL
	,NM_SEGMENTO_ECONOMICO	VARCHAR(100)	NOT	NULL
	,NM_EMPRESA				VARCHAR(100)	NOT	NULL
	,SG_EMPRESA				VARCHAR(100)	NOT	NULL
	,SG_EMPRESA_SEGMENTO	VARCHAR(100)	NULL
	,NR_HASH				FLOAT			NULL
)
GRANT ALL ON DATA_IMPORT.TB_TMP_RAW_BOVESPA_CLASSIFICACAO_SETORIAL TO CLASETORIAL

DROP TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO
DROP TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO
DROP TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO
DROP TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_EMPRESA

CREATE TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO
(
	CD_SETOR_ECONOMICO			INT				NOT	NULL IDENTITY (1,1)
	,NM_SETOR_ECONOMICO			VARCHAR(100)	NOT NULL
	,NR_SETOR_ECONOMICO_HASH	BIGINT			NOT	NULL
	,CONSTRAINT	PK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO PRIMARY KEY (CD_SETOR_ECONOMICO)
	--,CONSTRAINT AK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO UNIQUE (NR_SETOR_ECONOMICO_HASH)
)
GRANT ALL ON DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO TO CLASETORIAL

CREATE TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO
(
	CD_SUBSETOR_ECONOMICO		INT				NOT	NULL IDENTITY (1,1)
	,NM_SUBSETOR_ECONOMICO		VARCHAR(100)	NOT NULL
	,NR_SUBSETOR_ECONOMICO_HASH	BIGINT			NOT	NULL
	,CD_SETOR_ECONOMICO			INT				NOT	NULL
	,CONSTRAINT	PK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO PRIMARY KEY (CD_SUBSETOR_ECONOMICO)
	--,CONSTRAINT AK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO UNIQUE (NR_SUBSETOR_ECONOMICO_HASH)
	,CONSTRAINT FK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO FOREIGN KEY (CD_SETOR_ECONOMICO)
		REFERENCES DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO (CD_SETOR_ECONOMICO)
)
GRANT ALL ON DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO TO CLASETORIAL


CREATE TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO
(
	CD_SEGMENTO_ECONOMICO		INT				NOT	NULL IDENTITY (1,1)
	,NM_SEGMENTO_ECONOMICO		VARCHAR(100)	NOT NULL
	,NR_SEGMENTO_ECONOMICO_HASH	BIGINT			NOT	NULL
	,CD_SUBSETOR_ECONOMICO		INT				NOT	NULL
	,CONSTRAINT	PK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO PRIMARY KEY (CD_SEGMENTO_ECONOMICO)
	--,CONSTRAINT AK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO UNIQUE (NR_SEGMENTO_ECONOMICO_HASH)
	,CONSTRAINT FK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO FOREIGN KEY (CD_SUBSETOR_ECONOMICO)
		REFERENCES DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO (CD_SUBSETOR_ECONOMICO)
)
GRANT ALL ON DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO TO CLASETORIAL

CREATE TABLE DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_EMPRESA
(
	CD_EMPRESA					INT				NOT	NULL IDENTITY (1,1)
	,NM_EMPRESA					VARCHAR(100)	NOT NULL
	,SG_EMPRESA					VARCHAR(100)	NOT	NULL
	,SG_EMPRESA_SEGMENTO		VARCHAR(10)		NULL
	,NR_EMPRESA_HASH			FLOAT			NOT	NULL
	,CD_SEGMENTO_ECONOMICO		INT				NOT	NULL 
	,CONSTRAINT	PK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_EMPRESA PRIMARY KEY (CD_EMPRESA)
	,CONSTRAINT FK_TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO FOREIGN KEY (CD_SEGMENTO_ECONOMICO)
		REFERENCES DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO (CD_SEGMENTO_ECONOMICO)
)
GRANT ALL ON DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_EMPRESA TO CLASETORIAL


--CREATE PROC DATA_IMPORT.PR_ORGANIZAR_BOVESPA_CLASSIFICACAO_SETORIAL
--AS
--BEGIN


	if object_id('tempdb..#TB_TEMP_SETOR_ECONOMICO') is not null 
		drop table #TB_TEMP_SETOR_ECONOMICO
	if object_id('tempdb..#TB_TEMP_SUBSETOR_ECONOMICO') is not null 
		drop table #TB_TEMP_SUBSETOR_ECONOMICO
	if object_id('tempdb..#TB_TEMP_SEGMENTO_ECONOMICO') is not null 
		drop table #TB_TEMP_SEGMENTO_ECONOMICO
	if object_id('tempdb..#TB_TEMP_EMPRESA') is not null 
		drop table #TB_TEMP_EMPRESA
		
	SELECT 
		DISTINCT TB.NM_SETOR_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SETOR_ECONOMICO) AS BIGINT)	AS NR_SETOR_ECONOMICO_HASH		
		,CONVERT(INT,0)												AS CD_SETOR_ECONOMICO
		INTO
		#TB_TEMP_SETOR_ECONOMICO
	FROM
		 DATA_IMPORT.TB_TMP_RAW_BOVESPA_CLASSIFICACAO_SETORIAL TB

	SELECT 
		DISTINCT 
		TB.NM_SETOR_ECONOMICO											AS NM_SETOR_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SETOR_ECONOMICO) AS BIGINT)		AS NR_SETOR_ECONOMICO_HASH	
		,TB.NM_SUBSETOR_ECONOMICO										AS NM_SUBSETOR_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SUBSETOR_ECONOMICO) AS BIGINT)	AS NR_SUBSETOR_ECONOMICO_HASH		
		,CONVERT(INT,0)													AS CD_SETOR_ECONOMICO
		,CONVERT(INT,0)													AS CD_SUBSETOR_ECONOMICO
		INTO
		#TB_TEMP_SUBSETOR_ECONOMICO
	FROM
		 DATA_IMPORT.TB_TMP_RAW_BOVESPA_CLASSIFICACAO_SETORIAL TB

	SELECT 
		DISTINCT 
		TB.NM_SETOR_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SETOR_ECONOMICO) AS BIGINT) AS NR_SETOR_ECONOMICO_HASH	
		,TB.NM_SUBSETOR_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SUBSETOR_ECONOMICO) AS BIGINT) AS NR_SUBSETOR_ECONOMICO_HASH		
		,TB.NM_SEGMENTO_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SEGMENTO_ECONOMICO) AS BIGINT) AS NR_SEGMENTO_ECONOMICO_HASH		
		,CONVERT(INT,0)												AS CD_SETOR_ECONOMICO
		,CONVERT(INT,0)												AS CD_SUBSETOR_ECONOMICO
		,CONVERT(INT,0)												AS CD_SEGMENTO_ECONOMICO
		INTO
		#TB_TEMP_SEGMENTO_ECONOMICO
	FROM
		 DATA_IMPORT.TB_TMP_RAW_BOVESPA_CLASSIFICACAO_SETORIAL TB

	SELECT 
		DISTINCT 
		TB.NM_SETOR_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SETOR_ECONOMICO) AS BIGINT)		AS NR_SETOR_ECONOMICO_HASH	
		,TB.NM_SUBSETOR_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SUBSETOR_ECONOMICO) AS BIGINT)	AS NR_SUBSETOR_ECONOMICO_HASH		
		,TB.NM_SEGMENTO_ECONOMICO
		,CAST(HASHBYTES('SHA1', TB.NM_SEGMENTO_ECONOMICO) AS BIGINT)	AS NR_SEGMENTO_ECONOMICO_HASH		
		,CONVERT(INT,0)													AS CD_SETOR_ECONOMICO
		,CONVERT(INT,0)													AS CD_SUBSETOR_ECONOMICO
		,CONVERT(INT,0)													AS CD_SEGMENTO_ECONOMICO
		,CONVERT(INT,0)													AS CD_EMPRESA
		,NM_EMPRESA	
		,SG_EMPRESA	
		,SG_EMPRESA_SEGMENTO	
		,NR_HASH
		INTO
		#TB_TEMP_EMPRESA
	FROM
		 DATA_IMPORT.TB_TMP_RAW_BOVESPA_CLASSIFICACAO_SETORIAL TB

		 SELECT * FROM #TB_TEMP_EMPRESA

	BEGIN
		-- pegando os itens existentes
		UPDATE TMP
			SET TMP.CD_SETOR_ECONOMICO	=	FIM.CD_SETOR_ECONOMICO
		FROM
			#TB_TEMP_SETOR_ECONOMICO	TMP
		JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO	FIM
			ON FIM.NR_SETOR_ECONOMICO_HASH = TMP.NR_SETOR_ECONOMICO_HASH
	
		-- quem continuar com zero é novo e vai fazer insert
		INSERT INTO DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO 
		(
		NM_SETOR_ECONOMICO
		,NR_SETOR_ECONOMICO_HASH
		)
		SELECT 
			TMP.NM_SETOR_ECONOMICO, TMP.NR_SETOR_ECONOMICO_HASH
			FROM
				#TB_TEMP_SETOR_ECONOMICO	TMP
			WHERE
				CD_SETOR_ECONOMICO = 0
			ORDER BY 
				NM_SETOR_ECONOMICO

		UPDATE TMP
			SET TMP.CD_SETOR_ECONOMICO = FIM.CD_SETOR_ECONOMICO
			FROM
				#TB_TEMP_SUBSETOR_ECONOMICO TMP
			JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO	FIM
				ON FIM.NR_SETOR_ECONOMICO_HASH = TMP.NR_SETOR_ECONOMICO_HASH

		UPDATE TMP
			SET TMP.CD_SUBSETOR_ECONOMICO = FIM.CD_SUBSETOR_ECONOMICO
			FROM
				#TB_TEMP_SUBSETOR_ECONOMICO TMP
			JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO	FIM
				ON FIM.NR_SUBSETOR_ECONOMICO_HASH = TMP.NR_SUBSETOR_ECONOMICO_HASH
				AND FIM.CD_SETOR_ECONOMICO = TMP.CD_SETOR_ECONOMICO

		INSERT INTO DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO
		(
			NM_SUBSETOR_ECONOMICO		
			,NR_SUBSETOR_ECONOMICO_HASH	
			,CD_SETOR_ECONOMICO			
		)
		SELECT
			NM_SUBSETOR_ECONOMICO		
			,NR_SUBSETOR_ECONOMICO_HASH	
			,CD_SETOR_ECONOMICO	
			FROM
				#TB_TEMP_SUBSETOR_ECONOMICO TMP
			WHERE
				TMP.CD_SUBSETOR_ECONOMICO = 0
			ORDER BY 
				NM_SUBSETOR_ECONOMICO
		
		UPDATE TMP
			SET TMP.CD_SETOR_ECONOMICO = FIM.CD_SETOR_ECONOMICO
			FROM
				#TB_TEMP_SEGMENTO_ECONOMICO TMP
			JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO	FIM
				ON FIM.NR_SETOR_ECONOMICO_HASH = TMP.NR_SETOR_ECONOMICO_HASH

		UPDATE TMP
			SET TMP.CD_SUBSETOR_ECONOMICO = FIM.CD_SUBSETOR_ECONOMICO
			FROM
				#TB_TEMP_SEGMENTO_ECONOMICO TMP
			JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO	FIM
				ON FIM.NR_SUBSETOR_ECONOMICO_HASH = TMP.NR_SUBSETOR_ECONOMICO_HASH
				AND FIM.CD_SETOR_ECONOMICO = TMP.CD_SETOR_ECONOMICO
	
		UPDATE TMP
			SET TMP.CD_SUBSETOR_ECONOMICO = FIM.CD_SUBSETOR_ECONOMICO
			FROM
				#TB_TEMP_SEGMENTO_ECONOMICO TMP
			JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO	FIM
				ON FIM.CD_SEGMENTO_ECONOMICO = TMP.CD_SEGMENTO_ECONOMICO			
				AND FIM.CD_SUBSETOR_ECONOMICO = TMP.CD_SUBSETOR_ECONOMICO

		INSERT INTO DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO
		(
			NM_SEGMENTO_ECONOMICO		
			,NR_SEGMENTO_ECONOMICO_HASH	
			,CD_SUBSETOR_ECONOMICO			
		)
		SELECT
			NM_SEGMENTO_ECONOMICO		
			,NR_SEGMENTO_ECONOMICO_HASH	
			,CD_SUBSETOR_ECONOMICO	
			FROM
				#TB_TEMP_SEGMENTO_ECONOMICO TMP
			WHERE
				TMP.CD_SEGMENTO_ECONOMICO = 0
			ORDER BY 
				NM_SEGMENTO_ECONOMICO
	END
	
	UPDATE TMP
		SET TMP.CD_SETOR_ECONOMICO = FIM.CD_SETOR_ECONOMICO
		FROM
			#TB_TEMP_EMPRESA TMP
		JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO FIM
			ON FIM.NR_SETOR_ECONOMICO_HASH	=	TMP.NR_SETOR_ECONOMICO_HASH

	UPDATE TMP
		SET TMP.CD_SUBSETOR_ECONOMICO = FIM.CD_SUBSETOR_ECONOMICO
		FROM
			#TB_TEMP_EMPRESA TMP
		JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO FIM
			ON FIM.NR_SUBSETOR_ECONOMICO_HASH	=	TMP.NR_SUBSETOR_ECONOMICO_HASH
			AND FIM.CD_SETOR_ECONOMICO			=	TMP.CD_SETOR_ECONOMICO
	
	UPDATE TMP
		SET TMP.CD_SEGMENTO_ECONOMICO = FIM.CD_SEGMENTO_ECONOMICO
		FROM
			#TB_TEMP_EMPRESA TMP
		JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO FIM
			ON FIM.NR_SEGMENTO_ECONOMICO_HASH	=	TMP.NR_SEGMENTO_ECONOMICO_HASH
			AND FIM.CD_SUBSETOR_ECONOMICO			=	TMP.CD_SUBSETOR_ECONOMICO

	UPDATE TMP
		SET TMP.CD_EMPRESA = FIM.CD_EMPRESA
		FROM
			#TB_TEMP_EMPRESA TMP
		JOIN DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_EMPRESA FIM
			ON FIM.NR_EMPRESA_HASH					=	TMP.NR_HASH
			AND FIM.CD_SEGMENTO_ECONOMICO			=	TMP.CD_SEGMENTO_ECONOMICO

	INSERT INTO DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_EMPRESA	
	(				
		NM_EMPRESA				
		,SG_EMPRESA				
		,SG_EMPRESA_SEGMENTO	
		,NR_EMPRESA_HASH		
		,CD_SEGMENTO_ECONOMICO
	)
	SELECT
			NM_EMPRESA		
			,SG_EMPRESA	
			,SG_EMPRESA_SEGMENTO
			,NR_HASH
			,CD_SEGMENTO_ECONOMICO
			FROM
				#TB_TEMP_EMPRESA TMP
			WHERE
				TMP.CD_EMPRESA = 0
			ORDER BY 
				NM_EMPRESA


	SELECT * FROM DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SETOR_ECONOMICO --ORDER BY NR_SETOR_ECONOMICO_HASH
	SELECT * FROM DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SUBSETOR_ECONOMICO --ORDER BY NR_SUBSETOR_ECONOMICO_HASH
	SELECT * FROM DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_SEGMENTO_ECONOMICO --ORDER BY NM_SEGMENTO_ECONOMICO
	SELECT * FROM DATA_IMPORT.TB_BOVESPA_CLASSIFICACAO_SETORIAL_EMPRESA	
--END

